import { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, BarChart3, Bot, BrainCircuit, CheckCircle2, CircleDollarSign, Code2, Database, GitPullRequest, Home, Mail, Megaphone, Pause, Play, RefreshCw, Rocket, Search, Settings, ShieldCheck, Siren, TrendingUp, Users, WalletCards } from 'lucide-react';

type Agent={id:string;name:string;mission:string;risk:string;state:string;active_tasks:number};
type Task={id:string;title:string;owner:string;priority:string;state:string;updated_at?:string};
type Incident={id:string;title:string;severity:string;owner:string;status:string;updated_at?:string};
type Status={timestamp:string;agents:Agent[];tasks:Task[];incidents:Incident[];metrics:{active_agents:number;open_tasks:number;open_incidents:number;automation_health:number;pending_approvals:number};system?:{healthy?:boolean;checks?:Array<{name:string;ok:boolean}>}};

const API=(import.meta.env.VITE_API_URL||'http://localhost:3001/api').replace(/\/$/,'');
const fallbackAgents:Agent[]=[
{id:'ceo',name:'AI CEO',mission:'Vision, strategy & decisions',risk:'medium',state:'monitoring',active_tasks:0},
{id:'coo',name:'AI COO',mission:'Operations & execution',risk:'medium',state:'working',active_tasks:0},
{id:'cto',name:'AI CTO',mission:'Dev, infra & incident resolution',risk:'medium',state:'investigating',active_tasks:1},
{id:'qa',name:'QA Auditor',mission:'Testing & quality assurance',risk:'low',state:'monitoring',active_tasks:0},
{id:'security',name:'Security Auditor',mission:'Security, compliance & risks',risk:'high',state:'monitoring',active_tasks:0},
{id:'revenue',name:'Revenue Agent',mission:'Sales & revenue growth',risk:'medium',state:'working',active_tasks:0},
{id:'marketing',name:'Marketing Agent',mission:'Content, SEO & brand growth',risk:'medium',state:'monitoring',active_tasks:0},
{id:'finance',name:'Finance Agent',mission:'Accounting & financial ops',risk:'high',state:'monitoring',active_tasks:0},
{id:'trading_director',name:'Trading Director',mission:'Paper-trading oversight & risk controls',risk:'high',state:'monitoring',active_tasks:0},
{id:'comms',name:'Communications Agent',mission:'Email, Telegram & updates',risk:'low',state:'monitoring',active_tasks:0},
];

const iconMap:Record<string,any>={ceo:BrainCircuit,coo:Activity,cto:Code2,qa:CheckCircle2,security:ShieldCheck,revenue:CircleDollarSign,marketing:Megaphone,finance:WalletCards,trading_director:TrendingUp,comms:Mail};
const tone=(s:string)=>s==='paused'?'border-red-400/30 bg-red-400/10 text-red-300':s==='working'?'border-emerald-400/30 bg-emerald-400/10 text-emerald-300':s==='investigating'?'border-amber-400/30 bg-amber-400/10 text-amber-300':'border-blue-400/30 bg-blue-400/10 text-blue-300';
const nav=[['Home',Home],['Agents',Bot],['Tasks',CheckCircle2],['Incidents',AlertTriangle],['Repos',Code2],['Trading',TrendingUp],['Analytics',BarChart3],['Communications',Mail],['Knowledge',Database],['Settings',Settings]] as const;

export function AICompanyOS(){
 const[data,setData]=useState<Status|null>(null);const[loading,setLoading]=useState(false);const[err,setErr]=useState('');const[key,setKey]=useState(()=>sessionStorage.getItem('opexAiCompanyKey')||'');const[query,setQuery]=useState('');
 async function load(){setLoading(true);setErr('');try{const r=await fetch(`${API}/ai-company/status`);if(!r.ok)throw new Error(`Status API ${r.status}`);setData(await r.json());}catch(e){setErr(e instanceof Error?e.message:'Status unavailable');}finally{setLoading(false);}}
 useEffect(()=>{void load();const t=setInterval(()=>void load(),15000);return()=>clearInterval(t);},[]);
 async function agentAction(id:string,action:'pause'|'resume'|'run_now'){if(!key){setErr('Enter the control key to manage agents.');return;}sessionStorage.setItem('opexAiCompanyKey',key);const r=await fetch(`${API}/ai-company/agents/${id}/action`,{method:'POST',headers:{'Content-Type':'application/json','x-ai-company-key':key},body:JSON.stringify({action})});if(!r.ok){setErr(`Agent action failed (${r.status})`);return;}await load();}
 async function taskState(id:string,state:string){if(!key){setErr('Enter the control key to manage tasks.');return;}sessionStorage.setItem('opexAiCompanyKey',key);const r=await fetch(`${API}/ai-company/tasks/${id}/state`,{method:'POST',headers:{'Content-Type':'application/json','x-ai-company-key':key},body:JSON.stringify({state})});if(!r.ok){setErr(`Task update failed (${r.status})`);return;}await load();}
 const agents=data?.agents?.length?data.agents:fallbackAgents;const metrics=data?.metrics||{active_agents:agents.filter(a=>a.state!=='paused').length,open_tasks:data?.tasks?.filter(t=>!['done','cancelled'].includes(t.state)).length||0,open_incidents:data?.incidents?.filter(i=>i.status!=='closed').length||0,automation_health:data?.system?.healthy===false?70:100,pending_approvals:0};
 const events=useMemo(()=>{const items=[...(data?.incidents||[]).map(i=>({title:i.title,sub:`${i.owner} · ${i.status}`,time:i.updated_at||'' ,kind:'incident'})),...(data?.tasks||[]).map(t=>({title:t.title,sub:`${t.owner} · ${t.state}`,time:t.updated_at||'',kind:'task'}))];return items.sort((a,b)=>String(b.time).localeCompare(String(a.time))).slice(0,8);},[data]);
 const visibleAgents=agents.filter(a=>`${a.name} ${a.mission} ${a.state}`.toLowerCase().includes(query.toLowerCase()));
 return <section className="min-h-screen bg-[#06101f] text-white"><div className="flex min-h-screen">
  <aside className="hidden w-56 shrink-0 border-r border-white/10 bg-[#07111f] p-4 lg:block"><div className="mb-8 flex items-center gap-3 px-2"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-blue-500/20"><BrainCircuit className="h-6 w-6 text-blue-300"/></div><div><div className="font-black">OPEX AI</div><div className="text-xs text-slate-500">Company OS</div></div></div><nav className="space-y-1">{nav.map(([label,Icon],i)=><button key={label} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm ${i===0?'bg-blue-600/20 text-blue-200':'text-slate-400 hover:bg-white/5 hover:text-white'}`}><Icon className="h-4 w-4"/>{label}</button>)}</nav><div className="mt-10 rounded-2xl border border-blue-500/30 bg-blue-500/5 p-4 text-sm"><div className="font-bold">Build · Automate · Scale</div><div className="mt-2 text-xs text-slate-500">OPEX NINJA</div></div></aside>
  <main className="min-w-0 flex-1 p-4 sm:p-6"><div className="mx-auto max-w-[1600px]">
   <header className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div><div className="flex items-center gap-2"><BrainCircuit className="h-7 w-7 text-blue-400"/><h1 className="text-2xl font-black sm:text-3xl">OPEX AI Company OS</h1></div><p className="mt-1 text-sm text-slate-400">Autonomous Business & Operations Control Center</p></div><div className="flex flex-1 flex-wrap items-center justify-end gap-3"><div className="relative min-w-[240px] flex-1 xl:max-w-md"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-500"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search agents, tasks, repositories..." className="w-full rounded-xl border border-white/10 bg-white/5 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-blue-500/50"/></div><input value={key} onChange={e=>setKey(e.target.value)} type="password" placeholder="Control key" className="w-36 rounded-xl border border-white/10 bg-white/5 px-3 py-2.5 text-sm"/><button onClick={()=>void load()} className="rounded-xl border border-white/10 bg-white/5 p-2.5"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button><span className="rounded-xl border border-emerald-400/20 bg-emerald-400/10 px-3 py-2 text-xs font-bold text-emerald-300"><span className="mr-2 inline-block h-2 w-2 rounded-full bg-emerald-400"/>System Online</span></div></header>
   {err&&<div className="mt-4 rounded-xl border border-amber-400/20 bg-amber-400/10 px-4 py-3 text-sm text-amber-200">{err}</div>}
   <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{[
    ['Active Agents',`${metrics.active_agents}/${agents.length}`,Users,'text-blue-300'],['Open Tasks',metrics.open_tasks,CheckCircle2,'text-blue-300'],['Open Incidents',metrics.open_incidents,AlertTriangle,'text-red-300'],['Automation Health',`${metrics.automation_health}%`,Activity,'text-emerald-300'],['Revenue Opportunities','Tracking',CircleDollarSign,'text-blue-300'],['Pending Approvals',metrics.pending_approvals,Pause,'text-amber-300']
   ].map(([label,val,Icon,c])=><div key={String(label)} className="rounded-2xl border border-white/10 bg-white/[.045] p-4"><div className="flex items-center justify-between"><Icon className={`h-5 w-5 ${c}`}/><div className="h-8 w-20 rounded bg-gradient-to-r from-transparent via-white/5 to-white/10"/></div><div className="mt-3 text-2xl font-black">{String(val)}</div><div className="text-xs text-slate-500">{String(label)}</div></div>)}</div>
   <div className="mt-4 grid gap-4 2xl:grid-cols-[1fr_370px]"><div className="space-y-4"><section className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><div className="flex items-center justify-between"><div><h2 className="font-extrabold">Agent Workforce</h2><p className="text-xs text-slate-500">{agents.length} AI agents operating across your business</p></div><span className="text-xs text-blue-300">Realtime · 15s refresh</span></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-5">{visibleAgents.map(a=>{const Icon=iconMap[a.id]||Bot;return <article key={a.id} className="rounded-2xl border border-white/10 bg-[#0a1628] p-4"><div className="flex items-start justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-blue-500/10"><Icon className="h-6 w-6 text-blue-300"/></div><span className={`rounded-full border px-2 py-1 text-[10px] font-bold ${tone(a.state)}`}>{a.state}</span></div><h3 className="mt-3 font-bold">{a.name}</h3><p className="mt-1 min-h-[38px] text-xs leading-5 text-slate-500">{a.mission}</p><div className="mt-3 flex gap-2"><button onClick={()=>void agentAction(a.id,a.state==='paused'?'resume':'pause')} className="flex-1 rounded-lg border border-white/10 px-2 py-2 text-xs hover:bg-white/5">{a.state==='paused'?<Play className="mr-1 inline h-3 w-3"/>:<Pause className="mr-1 inline h-3 w-3"/>}{a.state==='paused'?'Resume':'Pause'}</button><button onClick={()=>void agentAction(a.id,'run_now')} className="rounded-lg border border-blue-400/20 bg-blue-400/10 px-2 py-2 text-xs text-blue-200">Run</button></div></article>})}</div></section>
    <section className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><div className="flex items-center justify-between"><div><h2 className="font-extrabold">Autonomous Workflow — From Issue to Deployment</h2><p className="text-xs text-slate-500">End-to-end incident resolution orchestrated by your AI team.</p></div><span className="rounded-full border border-blue-400/20 bg-blue-400/10 px-3 py-1 text-xs text-blue-200">Autonomous Execution</span></div><div className="mt-5 grid gap-2 md:grid-cols-9">{[['Issue Detected',AlertTriangle],['Incident Created',Siren],['CTO Assigned',Users],['Fix Prepared',Code2],['QA Review',CheckCircle2],['Security Check',ShieldCheck],['PR Ready',GitPullRequest],['Awaiting Approval',Pause],['Deployed',Rocket]].map(([label,Icon],i)=><div key={String(label)} className="text-center"><div className={`mx-auto flex h-11 w-11 items-center justify-center rounded-full border ${i===0?'border-red-400/40 bg-red-400/10':i===7?'border-amber-400/40 bg-amber-400/10':'border-blue-400/30 bg-blue-400/10'}`}><Icon className="h-5 w-5"/></div><div className="mt-2 text-[11px] font-semibold text-slate-300">{String(label)}</div></div>)}</div></section>
    <div className="grid gap-4 xl:grid-cols-[1.1fr_.9fr]"><section className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><h2 className="font-extrabold">Business Divisions</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[['Trading Division','Paper P&L','Guarded'],['OPEX Ninja Marketing','Campaigns','Active'],['Revenue & Leads','Pipeline','Tracking'],['Software & Repos','Deploy success',data?.system?.healthy===false?'Attention':'Healthy'],['Finance','AI/API spend','Tracking']].map(([a,b,c])=><div key={a} className="rounded-xl border border-white/10 bg-black/10 p-3"><div className="text-sm font-bold">{a}</div><div className="mt-4 text-xs text-slate-500">{b}</div><div className="mt-1 text-lg font-black text-emerald-300">{c}</div></div>)}</div></section><section className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><h2 className="font-extrabold">Tasks & Approvals</h2><div className="mt-3 space-y-2">{(data?.tasks||[]).slice(0,5).map(t=><div key={t.id} className="flex items-center gap-2 rounded-xl border border-white/10 p-3"><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold">{t.title}</div><div className="text-xs text-slate-500">{t.owner} · {t.priority}</div></div><select value={t.state} onChange={e=>void taskState(t.id,e.target.value)} className="rounded-lg border border-white/10 bg-[#07111f] px-2 py-1 text-xs">{['queued','assigned','working','blocked','review','waiting_approval','done','cancelled'].map(s=><option key={s}>{s}</option>)}</select></div>)}{!(data?.tasks||[]).length&&<div className="text-sm text-slate-500">No tasks recorded yet.</div>}</div></section></div></div>
    <aside className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><div className="flex items-center justify-between"><div><h2 className="font-extrabold">Live Activity Feed</h2><p className="text-xs text-slate-500">Real-time events from your AI workforce</p></div><span className="rounded-full bg-emerald-400/10 px-2 py-1 text-[10px] font-bold text-emerald-300">LIVE</span></div><div className="mt-4 space-y-2">{events.map((e,i)=><div key={`${e.title}-${i}`} className="rounded-xl border border-white/10 bg-[#0a1628] p-3"><div className="flex gap-3"><div className={`mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-lg ${e.kind==='incident'?'bg-red-400/10':'bg-blue-400/10'}`}>{e.kind==='incident'?<AlertTriangle className="h-4 w-4 text-red-300"/>:<CheckCircle2 className="h-4 w-4 text-blue-300"/>}</div><div className="min-w-0"><div className="text-sm font-semibold">{e.title}</div><div className="mt-1 text-xs text-slate-500">{e.sub}</div></div></div></div>)}{!events.length&&<div className="rounded-xl border border-white/10 p-4 text-sm text-slate-500">Waiting for live events…</div>}</div><div className="mt-5 rounded-xl border border-white/10 bg-black/10 p-4"><h3 className="text-sm font-bold">Guardrails & Approvals</h3><div className="mt-3 space-y-2 text-xs">{['Live trading (real money)','Payments / fund transfers','Credential changes','Destructive changes'].map(x=><div key={x} className="flex items-center justify-between gap-2"><span className="text-slate-400">{x}</span><span className="rounded-full bg-red-400/10 px-2 py-1 text-red-300">Requires Approval</span></div>)}</div></div><div className="mt-4 rounded-xl border border-blue-400/20 bg-blue-400/5 p-4"><div className="text-sm font-bold">Communications</div><div className="mt-3 flex items-center justify-between text-xs"><span>Telegram updates</span><span className="text-emerald-300">Configured by runtime</span></div><div className="mt-2 flex items-center justify-between text-xs"><span>Email EOD report</span><span className="text-blue-300">Scheduled</span></div></div></aside></div>
  </div></main></div></section>;
}
